version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      command:
        - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
        - sudo apt-get install python3.6
        - sudo pip install -U platformio
        - platformio lib -g install file://.
        - platformio platform install espressif8266
        - platformio lib -g install Shutters@2.1.1 SonoffDual@1.1.0
      - run:
          command: platformio ci ./NodeMCU/src/ --board=nodemcuv2
          name: Test

workflows:
  main:
    jobs:
      - build-and-test