machine:

  timezone:
    America/Los_Angeles # Set the timezone

  # Add some environment variables
  environment:
    WORK_DIR: ~/CS179J_test
    DISPLAY: :1.0

dependencies:
  pre:
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
    - sudo apt-get install python3.6
    - sudo pip install -U platformio
    - platformio lib -g install file://.
    - platformio platform install espressif8266
    - platformio lib -g install Shutters@2.1.1 SonoffDual@1.1.0
  override:

## Customize test commands
test:
  override:
    - platformio ci ./NodeMCU/src/ --board=nodemcuv2