version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: sudo pip install -U platformio
      - run: platformio platform install espressif8266
      - run: platformio ci ./NodeMCU/src/Server/belt_server/belt_server.ino --board=nodemcuv2